__all__ = [
    "CONFIG_KEY",
    "CONFIG_PATH_ENV_NAME",
    "DEFAULT_QUALIBRATE_CONFIG_FILENAME",
]

CONFIG_KEY = "qualibrate_composite"
DEFAULT_QUALIBRATE_CONFIG_FILENAME = "qualibrate.toml"
CONFIG_PATH_ENV_NAME = "QUALIBRATE_COMPOSITE_CONFIG_FILE"
