const cyKeys = {
  LOGIN_PAGE: "login-page",
  COMPONENTS_TAB: "components-tab",
  EXPERIMENTS_TAB: "experiments-tab",
  DASHBOARD_TAB: "dashboard-tab",
  PROJECT_TAB: "project-tab",
  DATA_TAB: "data-tab",
  HELP_TAB: "help-tab",
  TOGGLE_SIDEBAR: "toggle-sidebar",
  CALIBRATION_TAB: "calibration-tab",
  NODES_TAB: "nodes-tab",
  NOTEBOOK_TAB: "notebook-tab",
  DOCS_TAB: "docs-tab",
  SEARCH_TAB: "search-tab",
  ADMIN_PANEL_TAB: "admin-panel-tab",
  HOME_PAGE: "home-page",
  JOBS_TAB: "jobs-tab",
  NAVIGATION_SELECT_ITEM: "navigation-select-item",
  EDITABLE_CELL: "editable-cell",
  VALUE_ON_EDIT: "value-on-edit",
  login: {
    USERNAME: "username-field",
    PASSWORD: "login-field",
    SUBMIT: "login-button",
    LOGOUT_THUMBNAIL: "logout-thumbnail",
    LOGOUT_BUTTON: "logout-button",
  },
  experiment: {
    RUN_JOB_BUTTON: "experiment-run-job-button",
    SUBMIT_JOB_TO_QUEUE: "experiment-submit-job-to-queue",
    GRAPH: "graph",
    WORKFLOW_DESCRIPTION: "workflow-description",
    WORKFLOW_NAME: "workflow-name",
    WORKFLOW_VIEW: "workflow-view",
    CODE_VIEW: "code-view",
    SYSTEM_VIEW: "system-view",
    WORKFLOW_VIEW_BUTTON: "workflow-view-button",
    WORKFLOW_CODE_BUTTON: "workflow-code-button",
    WORKFLOW_SYSTEM_BUTTON: "workflow-system-button",
    EXPERIMENT_INFO: "experiment-info",
    PARAMETERS_PANEL: "parameters-panel",
    LOG_PANEL: "log-panel",
    DOCUMENTATION_PANEL: "documentation-panel",
    STATISTICS_PANEL: "statistics-panel",
    INPUT_TABLE: "input-table",
    nodeInfo: {
      edit: {
        INPUT: "node-info-edit-input",
        APPLY: "node-info-edit-apply",
      },
    },
  },
  projectPopup: {
    CHANGE_PROJECT: "change-project",
  },
  projects: {
    LETS_START_BUTTON: "lets-start-button",
    PROJECT: "project-item",
  },
  popup: {
    RUN_JOB_IN_WORKFLOW: "run-job-in-a-workflow",
    FILTER_EXPERIMENTS_POPUP: "filter-experiments-popup",
  },
  data: {
    MENU_BUTTON: "menu-button",
    EXPERIMENT: "data-experiment",
    EXPERIMENT_LIST: "data-experiment-list",
    FILTER_BUTTON: "filter-button",
  },
  jobs: {
    LIST: "job-list",
    WRAPPER: "job-wrapper",
    GROUP_SORT_BUTTON: "job-group-sort-button",
    START_DATE_SORT_BUTTON: "job-sort-date-button",
    FILTER_BUTTON: "job-filter-button",
    SELECT_JOB_BUTTON: "job-select-button",
    ADD_JOB_BUTTON: "job-add-job-button",
    EXISTING_WORKFLOW_BUTTON: "job-existing-workflow-button",
    ADD_JOB_POPUP: "add-job-popup",
    FILTER_JOBS_POPUP: "filter-jobs-popup",
    JOB_PARAMETERS: "job-parameters",
    JOB_STEP_NAME: "job-step-name",
    SELECT_CHECKBOX: "select-checkbox",
    COMPARE_BUTTON: "compare-button",
    DIFF_ROW: "diff-frame",
    JOB_COMPARE_SELECT: "job-compare-select",
    diff: {
      SELECT: "jobs-diff-select",
      SELECT_LIST_ITEM: "jobs-diff-select-list-item",
    },
  },
  table: {
    ROW: "table-row",
  },
  common: {
    DROPDOWN_LIST: "dropdown-list",
    PAGE_TITLE: "page-title",
    PAGE_SUBTITLE: "page-subtitle",
    DROPDOWN_BUTTON: "dropdown-button",
  },
};

export default cyKeys;
