name: Create draft GitHub release

on:
  push:
    tags:
      - v*

jobs:
  build:
    uses: qua-platform/qualibrate/.github/workflows/reusable-build.yaml@main
  release:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: dist
          pattern: python-package-sdist
      - name: Create release notes
        run: |
          cat > notes.md <<- EOM
          Qualibrate App package version:$(ls qualibrate-wheels/qualibrate_app-* | cut -d'-' -f3)
          Qualibrate Runner package version:$(ls qualibrate-wheels/qualibrate_runner-* | cut -d'-' -f3)
          Qualibrate Core package version:$(ls qualibrate-wheels/qualibrate_core-* | cut -d'-' -f3)
          EOM
      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          gh release create ${{ github.ref_name }}
          --notes-file notes.md
          --verify-tag --latest
          --draft
          "dist/qualibrate_core-${GITHUB_REF_NAME#v}.tar.gz"